// ══════════════════════════════════════════════════════════════════
//  MongoDB Init Script — runs ONCE on first container start
//  Creates indexes, collections, and a demo user
// ══════════════════════════════════════════════════════════════════

// Switch to banking database
db = db.getSiblingDB('bankingdb');

print('🔧 Initializing bankingdb...');

// ── Create collections ─────────────────────────────────────────────
db.createCollection('users');
db.createCollection('accounts');
db.createCollection('transactions');

// ── Create indexes ─────────────────────────────────────────────────
db.users.createIndex({ email: 1 },         { unique: true,  name: 'idx_email' });
db.users.createIndex({ accountNumber: 1 }, { unique: true, sparse: true, name: 'idx_account_number' });
db.accounts.createIndex({ userId: 1 },     { unique: true,  name: 'idx_account_userId' });
db.transactions.createIndex({ userId: 1, createdAt: -1 }, { name: 'idx_txn_user_date' });

print('✅ Indexes created');

// ── Demo user ──────────────────────────────────────────────────────
// NOTE: This user's password is "Test@1234"
// The real hash is generated by the Node.js app (bcrypt 12 rounds)
// This demo user is created WITHOUT password so it can be tested
// by registering a new user through the app

// Just verify the collections exist and indexes are set
var userCount = db.users.countDocuments();
print('📊 Current user count: ' + userCount);

print('');
print('✅ MongoDB bankingdb initialized successfully!');
print('');
print('📝 To test: Register a new user through the app at http://localhost');
print('   Or use the demo: admin@novabanc.com / Admin@1234 (created by app seed)');
print('');
